# -*- coding: utf-8 -*-
"""Group 12 - Raden Roro Anindya - Homework - Statistic.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17iSABdi4Qh6a79TltUPrnsXf4fBRT7Oq
"""

import pandas as pd
data = "https://drive.google.com/uc?id=1R2NaQokZtin3KNb2EVScccacexN9JzsG&export=download%27"
df = pd.read_csv(data)
df

"""# 1"""

# lihat data di kolom writing score
df['writing score']

"""# 2"""

# periksa deskripsi data di kolom writing score, gunakan fungsi describe()
df.describe()

"""# 3"""

# periksa nilai tengah data di kolom writing score, gunakan fungsi median()
df['writing score'].median()

"""# 4"""

# periksa modus data di kolom writing score, gunakan fungsi mode()
df['writing score'].mode()

"""# 5"""

# periksa berapa banyak data yang ada di kolom writing score, gunakan fungsi value_count().head(1)
df['writing score'].value_counts().head(1)

"""# 6"""

# buatkan grafik histogram dari data di kolom writing score
import matplotlib.pyplot as plt
plt.hist(df['writing score'], bins=10, edgecolor='white')
plt.title('writing score') # judul grafik
plt.xlabel('calculation score') # label sumbu x
plt.ylabel('frequency') # label sumbu y
plt.show()