# -*- coding: utf-8 -*-
"""Group 12 - Raden Roro Anindya - Homework - Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1175Lz4LapfMwpgfNthTCY9P4GqtqL5Sa

# 1
"""

# isi fungsi python yang tepat agar bisa menghasilkan output
print ('hello world')

"""# 2"""

# buatkan sebuah variabel yang bernama benda
# isi variabel tersebut dengan string "kursi"
# print variabel tersebut
benda = 'kursi'
print (f'{benda}')

"""# 3"""

# periksa tipe data pada variabel var
var = "buah"
type (var)

"""# 4"""

# ganti nilai temperatur menjadi 30, lalu print nilai temperatur
temperatur = 20 + 10
hasil = temperatur
print (f'hasil temperatur {hasil}')

"""# 5"""

# buatkan sebuah list yang berisi 5 nama buah
# lalu print nama buah yang berada pada index ke-3
buah = ['mangga', 'pisang', 'kurma', 'alpukat', 'kiwi']
print (buah [2])

"""# 6"""

# diberikan variabel suhu dengan nilai 27
# periksa apakah temperatur lebih dari 25, jika ya, print "panas", jika tidak, print "dingin"
suhu = 27
if suhu > 25:
    print('panas')
else:
    print('dingin')

"""# 7"""

# terdapat variabel judul dengan semua huruf kecil
# ubahlah judul tersebut menjadi semua hurufnya kapital
judul = "belajar python"
kapital = judul.upper()
print(f'{kapital}')