# -*- coding: utf-8 -*-
"""Group 12 - Raden Roro Anindya - Homework - ML.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kdpW02hMBSbY0p2EUfu_zhplVnXVxnQ9

# Before you start, please make sure to **make a copy** on it

# Teori

## 1. Jelaskan perbedaan supervised dengan unsupervised learning, serta berikan contoh!

Jawab: Supervised adalah jenis ML yang melibatkan pelatihan model menggunakan data yang sudah diberi label, contohnya model dilatih dengan data medis berlabel untuk memprediksi apakah seorang pasien mengidap penyakit tertentu. Unsupervised adalah jenis ML yang menggunakan data tanpa label untuk menemukan pola tersembunyi, contohnya mengelompokkan lagu berdasarkan kesamaan nada dan genre tanpa informasi sebelumnya tentang kategorinya.

# Hands on
"""

import pandas as pd

salary = pd.read_csv('https://github.com/ybifoundation/Dataset/raw/main/Salary%20Data.csv')
salary.head()

y = salary['Salary']
X = salary[['Experience Years']]

"""## Bagi data dengan mengisi 20% pada train_size, serta gunakan random_state 42"""

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, train_size=0.2, random_state=42)

X_train.shape, X_test.shape, y_train.shape, y_test.shape

"""## Gunakan model linear regression, lalu latih model dengan X_train dan y_train menggunakan .fit()"""

from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train, y_train)

"""## Lihat nilai R-squared, kemudian apa interpretasinya?


"""

from sklearn.metrics import mean_squared_error,r2_score
r2 = r2_score(y_test, model.predict(X_test))
print(f"R-squared: {r2:.4f}")

"""Jawab: Model ini memiliki akurasi tinggi yaitu sebesar 95.43% karena sebagian besar perubahan gaji dapat diprediksi berdasarkan pengalaman kerja

## Lihat visualisasi hasil, apa yang bisa disimpulkan dari plot tersebut?
"""

import matplotlib.pyplot as plt
# Plotting the linear regression line
plt.scatter(y_test, model.predict(X_test), alpha=0.7, label='Predicted')
plt.plot([min(y_test), max(y_test)], [min(y_test), max(y_test)], linestyle='--', color='red', label='Perfect Prediction')
plt.xlabel('Actual Values')
plt.ylabel('Predicted Values')
plt.title('Predicted vs. Actual Values')
plt.legend()
plt.show()

"""Jawab: Titik biru cukup dekat dengan garis merah putus-putus menunjukkan model dapat memprediksi gaji berdasarkan pengalaman kerja dengan baik, namun ada beberapa titik biru menyimpang dari garis merah putus-putus yang berarti ada beberapa prediksi yang tidak sepenuhnya akurat

"""